/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atomic_broadcast;

import atomic_broadcast.utils.CompositeModule;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        CompositeModule modules = new CompositeModule();

        modules.add(new AeronModule(true, true, false));

        modules.start();

        modules.close();
    }
}
